WIP on label_api_snapshot.yml workflow.

diff --git a/.github/workflows/label_api_snapshot.yml b/.github/workflows/label_api_snapshot.yml
--- a/.github/workflows/label_api_snapshot.yml
+++ b/.github/workflows/label_api_snapshot.yml
@@ -23,9 +23,9 @@ jobs:
       uses: actions/checkout@v2
     - name: Verify Label
       if: ${{ !env.LABEL }}
-      run: 'echo "Missing client_payload parameter: label" || exit 1'
+      run: 'echo "Missing client_payload parameter: label" ; exit 1'
     - name: Verify Snapshot ID
       if: ${{ !env.SNAPSHOT_ID }}
-      run: 'echo "Missing client_payload parameter: snapshot_id" || exit 1'
+      run: 'echo "Missing client_payload parameter: snapshot_id" ; exit 1'
     - name: Create Label
       run: echo "Creating label '${{env.LABEL}}' to '/snapshot/${{ env.SNAPSHOT_ID }}'"
